<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>IncidentReview.Domain</AssemblyName>
    <RootNamespace>IncidentReview.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../IncidentReview.Results/IncidentReview.Results.csproj" />
  </ItemGroup>
</Project>
