<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>IncidentReview.EventSync.Http</AssemblyName>
    <RootNamespace>IncidentReview.EventSync.Http</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../IncidentReview.EventSync.Contracts/IncidentReview.EventSync.Contracts.csproj" />
    <ProjectReference Include="../IncidentReview.Domain/IncidentReview.Domain.csproj" />
    <ProjectReference Include="../IncidentReview.Results/IncidentReview.Results.csproj" />
  </ItemGroup>
</Project>
