<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>IncidentReview.Store.Contracts</AssemblyName>
    <RootNamespace>IncidentReview.Store.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../IncidentReview.Domain/IncidentReview.Domain.csproj" />
    <ProjectReference Include="../IncidentReview.Results/IncidentReview.Results.csproj" />
  </ItemGroup>
</Project>
